# 預設環境 (staging)
name = "lingubible-staging"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "VITE_APPWRITE_ENDPOINT=https://fra.cloud.appwrite.io/v1 VITE_APPWRITE_PROJECT_ID=lingubible bun run build:cf-fast"
cwd = ""
watch_dir = "src"

# 靜態資源配置 - 用於 SPA
[assets]
directory = "./dist"
not_found_handling = "single-page-application"

# 觀察性設定 - 啟用日誌記錄以確保部署設定一致性
[observability.logs]
enabled = true

# 生產環境配置
[env.production]
name = "lingubible"
# 生產環境使用相同的靜態資源配置