name = "lingubible"
compatibility_date = "2025-06-30"

[build]
command = "bun install --frozen-lockfile && VITE_APPWRITE_ENDPOINT=https://fra.cloud.appwrite.io/v1 VITE_APPWRITE_PROJECT_ID=lingubible bun run build"

# 環境變數在構建命令中設置

# 靜態資源配置 - 用於 SPA
[assets]
directory = "./dist"
not_found_handling = "single-page-application"

# 觀察性設定 - 啟用日誌記錄以確保部署設定一致性
[observability.logs]
enabled = true