import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { Language } from '@/components/LanguageSwitcher';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string, params?: Record<string, any>) => any;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Cookie helper functions
const getCookie = (name: string): string | null => {
  const value = `; ${document.cookie}`;
  const parts = value.split(`; ${name}=`);
  if (parts.length === 2) return parts.pop()?.split(';').shift() || null;
  return null;
};

const setCookie = (name: string, value: string, days: number = 365) => {
  const expires = new Date();
  expires.setTime(expires.getTime() + days * 24 * 60 * 60 * 1000);
  document.cookie = `${name}=${value};expires=${expires.toUTCString()};path=/`;
};

// Get initial language from cookie or detect from system
const getInitialLanguage = (): Language => {
  if (typeof window === 'undefined') return 'en'; // SSR safety
  
  const savedLanguage = getCookie('language');
  if (savedLanguage && ['en', 'zh-TW', 'zh-CN'].includes(savedLanguage)) {
    return savedLanguage as Language;
  }
  
  // 如果沒有保存的語言，檢測系統語言
  const browserLang = navigator.language || navigator.languages?.[0];
  let detectedLanguage: Language = 'en'; // 默認英文
  
  if (browserLang) {
    console.log('檢測到的瀏覽器語言:', browserLang);
    
    if (browserLang.startsWith('zh-TW') || 
        browserLang.startsWith('zh-Hant') || 
        browserLang === 'zh-HK' || 
        browserLang === 'zh-MO') {
      detectedLanguage = 'zh-TW';
    } else if (browserLang.startsWith('zh-CN') || 
               browserLang.startsWith('zh-Hans') || 
               browserLang.startsWith('zh-SG') || 
               browserLang === 'zh') {
      detectedLanguage = 'zh-CN';
    } else if (browserLang.startsWith('en')) {
      detectedLanguage = 'en';
    } else {
      // 對於其他語言，默認使用英文
      detectedLanguage = 'en';
    }
  }
  
  console.log('自動檢測語言設定為:', detectedLanguage);
  
  // 自動保存檢測到的語言到 cookie
  setCookie('language', detectedLanguage);
  
  return detectedLanguage;
};

const translations = {
  en: {
    // Site metadata
    'site.name': 'LingUBible',
    'site.title': 'LingUBible - Course & Lecturer Reviews',
    'site.description': 'Platform for college students to review courses and lecturers',
    'hero.title': 'Welcome to',
    'hero.subtitle': 'Your platform for honest course and lecturer reviews. Help fellow students make informed decisions',
    'hero.action': 'comment',
    'hero.actions': ['comment', 'vote', 'ask', 'answer'],
    'hero.getStarted': 'Get Started',
    'hero.comeHereTo': 'Come here to',
    'nav.home': 'Home',
    'nav.courses': 'Courses',
    'nav.lecturers': 'Lecturers',
    'nav.about': 'About',
    'nav.signIn': 'Sign In',
    'stats.totalCourses': 'Total Courses',
    'stats.lecturers': 'Lecturers',
    'stats.reviews': 'Reviews',
    'stats.activeStudents': 'Active Students',
    'stats.thisMonth': 'this month',
    'tabs.popularCourses': 'Popular Courses',
    'tabs.topLecturers': 'Top Lecturers',
    'footer.builtWith': 'Built with 💝 by ansonlo.dev',
    'footer.disclaimer': 'The website is not affiliated with Lingnan University',
    // Footer additional
    'footer.builtWithTools': 'Built with open-source tools by',
    'footer.beta': 'BETA',
    'footer.version': 'Version 0.0.1',
    'footer.contact': 'Contact',
    'footer.terms': 'Terms',
    'footer.privacy': 'Privacy',
    // Auth Modal
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.enterEmail': 'Enter your email',
    'auth.enterPassword': 'Enter your password',
    'auth.confirmPasswordPlaceholder': 'Confirm your password',
    'auth.alreadyHaveAccount': 'Already have an account? Sign in',
    'auth.dontHaveAccount': "Don't have an account? Sign up",
    'auth.passwordMismatch': 'Passwords do not match',
    'auth.passwordMatch': 'Passwords match',
    'auth.rememberMe': 'Remember me',
    'auth.authFailed': 'Authentication failed, please check your information',
    'auth.pleaseVerifyStudentEmail': 'Please verify your Lingnanians email address first',
    'auth.passwordNotSecure': 'Password does not meet security requirements, please check the password strength indicator',
    'auth.passwordTooShort': 'Password must be between 8 and 256 characters long',
    'auth.rateLimitExceeded': 'Rate limit exceeded. Please try again after some time',
    'auth.secureConnection': 'Your credentials will be encrypted and sent in a secure connection.',
    'auth.schoolPasswordReminder': 'Please do not use the same password as your university webmail account. For account security, we recommend using different passwords for each service.',
    'auth.forgotPassword': 'Forgot password?',
    'auth.resetPassword': 'Reset Password',
    'auth.sendResetEmail': 'Send Reset Email',
    'auth.resetEmailSent': 'Password reset email has been sent to your email address.',
    'auth.studentVerificationSuccess': 'Lingnanians email verification successful! You can now set up your password to complete registration.',
    'auth.backToLogin': 'Back to Login',
    'auth.backToHome': 'Back to Home',
    'auth.noAccount': "Don't have an account?",
    'auth.haveAccount': 'Already have an account?',
    'auth.contact': 'Contact',
    'auth.terms': 'Terms',
    'auth.privacy': 'Privacy',
    'auth.help': 'Help Center',
    // Auth page titles and descriptions
    'auth.welcomeBack': 'Welcome back',
    'auth.createStudentAccount': 'Create your Lingnanians account',
    'auth.fillInfoToCreate': 'Fill in the following information to create your Lingnanians account',
    'auth.studentInfoVerification': 'Lingnanians Information Verification',
    'auth.passwordSetup': 'Password Setup',
    'auth.usernameSetup': 'Username Setup',
    'auth.username': 'Username',
    'auth.usernamePlaceholder': 'Enter your username (2-10 characters)',
    'auth.usernameAvailable': 'Username available',
    'auth.usernameRules': 'Username Rules:',
    'auth.usernameLength': '• Length: 2-10 characters',
    'auth.usernameSupported': '• Supports: Chinese, English, numbers, symbols, spaces',
    'auth.usernameDisplay': '• Username will be displayed in profile and comments',
    'auth.usernameModifiable': '• Can be modified in settings after registration',
    'auth.usernameSuggestion': 'Suggested username:',
    'auth.useSuggestion': 'Use',
    'auth.enterAccountInfo': 'Enter your account information to sign in',
    'auth.resetYourPassword': 'Reset your password',
    'auth.signOut': 'Sign Out',
    // Toast messages
    'toast.loginSuccess': 'Login Successful!',
    'toast.welcomeBack': 'Welcome back, {username}!',
    'toast.registerSuccess': 'Registration Successful!',
    'toast.welcomeToApp': 'Welcome to LingUBible, {username}!',
    'toast.logoutSuccess': 'Logout Successful',
    'toast.goodbye': 'Goodbye, {username}! Looking forward to your next visit.',
    // Search
    'search.placeholder': 'Search courses, lecturers...',
    // Buttons
    'button.viewAll': 'View All',
    'button.review': 'Review',
    'button.viewDetails': 'View Details',
    'button.viewProfile': 'View Profile',
    // Course/Lecturer Cards
    'card.reviews': 'reviews',
    'card.students': 'students',
    'card.courses': 'courses',
    'card.specialties': 'Specialties',
    'card.more': 'more',
    'card.prof': 'Prof.',
    // Difficulty levels
    'difficulty.easy': 'Easy',
    'difficulty.medium': 'Medium',
    'difficulty.hard': 'Hard',
    // Departments
    'department.computerScience': 'Computer Science',
    'department.mathematics': 'Mathematics',
    'department.english': 'English',
    // Specialties
    'specialty.programming': 'Programming',
    'specialty.dataStructures': 'Data Structures',
    'specialty.algorithms': 'Algorithms',
    'specialty.machineLearning': 'Machine Learning',
    'specialty.calculus': 'Calculus',
    'specialty.linearAlgebra': 'Linear Algebra',
    'specialty.statistics': 'Statistics',
    'specialty.literature': 'Literature',
    'specialty.creativeWriting': 'Creative Writing',
    'specialty.poetry': 'Poetry',
    'specialty.drama': 'Drama',
    // Sample course titles
    'course.introCS': 'Introduction to Computer Science',
    'course.advancedMath': 'Advanced Mathematics',
    'course.englishLit': 'English Literature',
    // Sidebar
    'sidebar.myReviews': 'My Reviews',
    'sidebar.trending': 'Trending',
    'sidebar.settings': 'Settings',
    // Password Security
    'password.strength': 'Password Strength',
    'password.requirements': 'Password Requirements:',
    'password.length': 'Password length 8-40 characters',
    'password.uppercase': 'Contains at least 1 uppercase letter',
    'password.lowercase': 'Contains at least 1 lowercase letter',
    'password.special': 'Contains at least 1 special character (!@#$%^&* etc.)',
    'password.number': 'Contains at least 1 number',
    'password.notCommon': 'Not a common password',
    'password.notLeaked': 'Does not match known leaked password patterns',
    'password.notSimilarToEmail': 'Should not be similar to school email address',
    'password.lengthSuggestion': 'Recommend using 12+ characters for better security',
    'password.weak': 'Weak',
    'password.fair': 'Fair',
    'password.good': 'Good',
    'password.strong': 'Strong',
    'password.securityReminder': 'Security Reminder:',
    'password.schoolEmailWarning': 'Please do not use the same password as your university webmail account. For account security, we recommend using different passwords for each service.',
    'password.commonPasswordDanger': 'Danger:',
    'password.commonPasswordMessage': 'You are using a common password that is easily cracked. Please choose a more secure password.',
    'password.leakedPasswordRisk': 'High Risk:',
    'password.leakedPasswordMessage': 'This password matches known leaked password patterns and is extremely vulnerable to attackers. Please change to a more secure password immediately.',
    // Forgot password page
    'auth.emailSent': 'Email Sent',
    'auth.checkYourEmail': 'Please check your email',
    'auth.resetLinkSent': 'We have sent a password reset link to',
    'auth.resetLinkSentComplete': 'sent a password reset link.',
    'auth.checkSpamFolder': 'If you did not receive the email, please check your spam folder.',
    'auth.enterSchoolEmail': 'Enter your school email address and we will send you a reset link',
    'auth.schoolEmailPlaceholder': 'student@ln.hk or student@ln.edu.hk',
    'auth.useSchoolEmail': 'Please use your school email address (@ln.hk or @ln.edu.hk)',
    'auth.sendResetFailed': 'Failed to send reset email, please try again later',
    'auth.sending': 'Sending...',
    'auth.securityReminder': 'Security Reminder',
    'auth.resetLinkExpiry': 'The reset link will expire in 24 hours. If you did not request a password reset, please ignore this email.',
    'auth.resetLinkWillExpire': 'Reset link will expire in 24 hours',
    'auth.checkEmailInbox': 'Please check your inbox:',
    'auth.canRetryReset': 'You can retry sending reset email',
    'auth.resendReset': 'Resend',
    'auth.sendResetLink': 'Send Reset Link',
    'auth.studentEmailAddress': 'Lingnanians Email Address',
    'auth.resetPasswordDescription': 'Enter your Lingnanians email address and we will send you a reset link',
    'auth.emailNotRegistered': 'This email address is not registered. Please register first or check your email address.',
    'auth.checkingEmailExists': 'Checking if email is registered...',
    'auth.emailRegistered': 'Email address is registered',
    'auth.invalidCredentials': 'Invalid email or password. Please check and try again.',
    'auth.registrationFailed': 'Registration failed. Please check your information and try again.',
    // Processing
    'auth.processing': 'Processing...',
    // Email placeholder
    'auth.emailPlaceholder': 'student@ln.hk or student@ln.edu.hk',
    // Email validation
    'auth.invalidStudentEmail': 'This email address is not a valid Lingnanians email address. Please use a valid @ln.hk or @ln.edu.hk email address.',
    // Email checking status
    'auth.checkingEmail': 'Checking email availability...',
    'auth.checkingAccount': 'Checking account...',
    'auth.emailAvailable': 'Email address available',
    // Student verification
    'verification.title': 'Lingnanians Email Verification',
    'verification.sendCode': 'Send Verification Code',
    'verification.onlyStudentEmails': 'Only @ln.hk or @ln.edu.hk email addresses can register',
    'verification.codeExpiry': 'Verification code valid for 10 minutes',
    'verification.maxAttempts': 'Maximum attempts to verify 3 times',
    'verification.resendAfter': 'Can resend after',
    'verification.enterCode': 'Enter 6-digit verification code',
    'verification.verifying': 'Verifying...',
    'verification.verify': 'Verify',
    'verification.resend': 'Resend',
    'verification.sendingCode': 'Sending verification code...',
    'verification.codeSent': 'Verification code has been sent to your email address, please check your inbox',
    'verification.verifyFailed': 'Verification failed',
    // Email reminder
    'email.reminder.title': '📧 Email Delivery Reminder',
    'email.reminder.checkSpam': 'If you don\'t receive the email, please check your spam/junk folder',
    'email.reminder.whitelist': 'Consider adding noreply@lingubible.com to your email whitelist',
    'email.reminder.deliveryTime': 'Email delivery may take 1-2 minutes',
    'email.reminder.contactSupport': 'If you still don\'t receive the email after 5 minutes, please contact support',
    // Password strength
    'password.strengthLabel': 'Strength:',
    // Swipe hint
    'swipe.hint': 'Swipe right anywhere on screen to open menu',
    'swipe.dismissHint': 'Scroll to dismiss hint',
    // Cookie consent
    'cookie.title': 'Cookie Consent',
    'cookie.description': 'This website uses cookies to ensure you get the best browsing experience.',
    'cookie.accept': 'Accept',
    'cookie.learnMore': 'Learn More',
    'cookie.decline': 'Decline',
    'cookie.close': 'Close',
    // Cookie policy details
    'cookie.policy.title': 'How We Use Cookies',
    'cookie.policy.intro': 'We use cookies to enhance your browsing experience and improve our services. Here\'s how:',
    'cookie.policy.essential.title': 'Essential Cookies',
    'cookie.policy.essential.desc': 'These cookies are necessary for the website to function properly. They enable basic features like page navigation, user authentication, and security.',
    'cookie.policy.functional.title': 'Functional Cookies',
    'cookie.policy.functional.desc': 'These cookies remember your preferences (like language settings, theme, and sidebar state) to provide a personalized experience.',
    'cookie.policy.analytics.title': 'Analytics Cookies',
    'cookie.policy.analytics.desc': 'We use these cookies to understand how visitors interact with our website, helping us improve performance and user experience.',
    'cookie.policy.types': 'Types of cookies we use:',
    'cookie.policy.type1': '• Authentication cookies to keep you logged in',
    'cookie.policy.type2': '• Language preference cookies',
    'cookie.policy.type3': '• Theme and layout preference cookies',
    'cookie.policy.type4': '• Anonymous usage analytics',
    'cookie.policy.retention': 'Cookie Retention',
    'cookie.policy.retention.desc': 'Most cookies are stored for up to 1 year, while session cookies are deleted when you close your browser.',
    'cookie.policy.control': 'Your Control',
    'cookie.policy.control.desc': 'You can control cookies through your browser settings. However, disabling certain cookies may affect website functionality.',
    'cookie.policy.contact': 'If you have questions about our cookie policy, please contact us.',
    // PWA Install
    'pwa.installAvailable': 'App Available',
    'pwa.installDescription': 'Install LingUBible for a better experience',
    'pwa.installBenefits': 'Faster loading, offline access, and native app experience',
    'pwa.install': 'Install',
    'pwa.installApp': 'Install App',
    'pwa.howToInstall': 'How to Install',
    'pwa.notNow': 'Not Now',
    'pwa.dismiss': 'Dismiss',
    'pwa.gotIt': 'Got It',
    'pwa.installSuccess': 'App installed successfully!',
    'pwa.installFailed': 'Installation failed. Please try again.',
    'pwa.alreadyInstalled': 'App is already installed',
    'pwa.updateAvailable': 'App update available',
    'pwa.updateNow': 'Update Now',
    'pwa.updateLater': 'Update Later',
    // User Stats
    'stats.onlineUsers': 'Online Users',
    'stats.totalRegistered': 'Total Registered',
    'stats.todayLogins': 'Today Logins',
    'stats.thisMonthLogins': 'This Month',
    'stats.usersOnline': 'users online',
    'stats.loading': 'Loading...',
    // OpenStatus
    'status.operational': 'Operational',
    'status.degraded': 'Degraded',
    'status.down': 'Down',
    'status.checking': 'Checking',
    'status.poweredBy': 'Powered by OpenStatus',
    // Avatar
    'avatar.customize': 'Customize Avatar',
    'avatar.combinations': 'combinations',
    'avatar.preview': 'Preview',
    'avatar.randomize': 'Randomize',
    'avatar.save': 'Save Avatar',
    'avatar.saving': 'Saving...',
    'avatar.resetToDefault': 'Reset to Default',
    'avatar.animals': 'Animals',
    'avatar.backgrounds': 'Backgrounds',
    'avatar.totalStats': '{animals} animals × {backgrounds} backgrounds = {total} combinations',
    'avatar.saveSuccess': 'Avatar saved',
    'avatar.saveSuccessDesc': 'Your custom avatar has been successfully saved to the cloud',
    'avatar.saveFailed': 'Save failed',
    'avatar.saveFailedDesc': 'Unable to save avatar, please try again later',
    'avatar.resetSuccess': 'Avatar reset',
    'avatar.resetSuccessDesc': 'Restored to system default avatar',
    'avatar.deleteFailed': 'Delete failed',
    'avatar.deleteFailedDesc': 'Unable to delete avatar, please try again later',
    'avatar.saveError': 'Save failed, please try again',
    // Background colors
    'background.sunset': 'Sunset',
    'background.peach': 'Peach',
    'background.coral': 'Coral',
    'background.rose': 'Rose',
    'background.ocean': 'Ocean',
    'background.sky': 'Sky',
    'background.mint': 'Mint',
    'background.forest': 'Forest',
    'background.lavender': 'Lavender',
    'background.grape': 'Grape',
    'background.plum': 'Plum',
    'background.cloud': 'Cloud',
    'background.stone': 'Stone',
    'background.warm': 'Warm',
    'background.rainbow': 'Rainbow',
    'background.aurora': 'Aurora',
    'background.cosmic': 'Cosmic',
    'background.tropical': 'Tropical',
    'background.fire': 'Fire',
    'background.ice': 'Ice',
    // Terms of Service
    'terms.title': 'Terms of Service',
    'terms.lastUpdated': 'Last updated: June 5, 2025',
    'terms.welcome': 'Welcome to LingUBible',
    'terms.acceptance.title': '1. Acceptance of Terms',
    'terms.acceptance.content': 'By using this website, you agree to comply with these terms of service. If you do not agree to these terms, please do not use this service.',
    'terms.conduct.title': '2. User Conduct Guidelines',
    'terms.conduct.content': 'To maintain a positive community environment, users must follow these conduct guidelines:',
    'terms.conduct.noSwearing': '• No profanity or inappropriate language',
    'terms.conduct.noPersonalAttacks': '• No personal attacks or malicious comments targeting individuals',
    'terms.conduct.noSpam': '• No spam or repetitive meaningless content',
    'terms.conduct.respectful': '• Maintain respectful and constructive discussion',
    'terms.conduct.violation': 'Violation of these guidelines may result in account suspension or permanent ban',
    'terms.moderation.title': '3. Content Moderation',
    'terms.moderation.content': 'We reserve the right to moderate and manage platform content:',
    'terms.moderation.removal': '• Inappropriate comments will be removed without prior notice',
    'terms.moderation.standards': '• We are committed to maintaining a high-quality discussion environment',
    'terms.moderation.discretion': '• Moderation decisions are based on community guidelines and management team judgment',
    'terms.privacy.title': '4. Privacy Protection',
    'terms.privacy.content': 'We are committed to protecting your privacy:',
    'terms.privacy.anonymity': '• Commenter identities will be kept strictly confidential',
    'terms.privacy.noDisclosure': '• We will not disclose user identity information to any third parties',
    'terms.privacy.dataCollection': '• For detailed data collection policies, please refer to our Privacy Policy',
    'terms.changes.title': '5. Terms Changes',
    'terms.changes.content': 'We may update these terms from time to time. Major changes will be announced through website notifications.',
    'terms.contact.title': '8. Contact Us',
    'terms.contact.content': 'If you have any questions about these terms, please contact us through the website contact feature.',
    'terms.username.title': '6. Username Policy',
    'terms.username.content': 'Users are responsible for their chosen usernames:',
    'terms.username.offensive': '• Offensive, inappropriate, or misleading usernames may be changed without notice',
    'terms.username.discretion': '• Username changes are at the discretion of the management team',
    'terms.username.responsibility': '• Users are responsible for ensuring their usernames comply with community standards',
    'terms.content.title': '7. Content Policy',
    'terms.content.content': 'To maintain a focused and relevant discussion environment:',
    'terms.content.noPolitics': '• Political discussions are not permitted',
    'terms.content.noReligion': '• Religious discussions are not permitted',
    'terms.content.noUnrelated': '• Content unrelated to the site\'s purpose is not permitted',
    'terms.content.removal': 'Unrelated or inappropriate content will be removed without notice',
    'terms.content.focus': '• Please keep discussions focused on course and lecturer reviews',
    // Privacy Policy
    'privacy.title': 'Privacy Policy',
    'privacy.lastUpdated': 'Last updated: June 5, 2025',
    'privacy.intro': 'This privacy policy explains how we collect, use, and protect your personal information.',
    'privacy.dataCollection.title': '1. Data Collection',
    'privacy.dataCollection.content': 'To provide better services and maintain platform security, we collect the following information:',
    'privacy.dataCollection.sessionTime': 'Session time: Used to analyze user activity and improve service quality',
    'privacy.dataCollection.ipAddress': 'IP address: Used for security monitoring and preventing abuse',
    'privacy.dataCollection.userAgent': 'Browser information: Used to optimize website compatibility and user experience',
    'privacy.dataCollection.purpose': 'The purpose of collecting this information is to:',
    'privacy.dataCollection.security': '• Maintain platform security and prevent malicious attacks and abuse',
    'privacy.dataCollection.analytics': '• Analyze user behavior to improve service quality',
    'privacy.dataCollection.technical': '• Provide technical support and troubleshooting',
    'privacy.dataCollection.compliance': '• Comply with legal and regulatory requirements',
    'privacy.anonymity.title': '2. Anonymity Protection',
    'privacy.anonymity.content': 'We highly value user anonymity:',
    'privacy.anonymity.strictConfidentiality': 'Commenter identity information will be kept strictly confidential',
    'privacy.anonymity.noDisclosure': 'We promise not to disclose user real identities to any individuals, organizations, or third parties',
    'privacy.anonymity.internalAccess': 'Only authorized technical personnel can access user data when necessary, and only for technical maintenance',
    'privacy.anonymity.legalProtection': 'Unless explicitly required by law, we will not proactively disclose user information',
    'privacy.dataRetention.title': '3. Data Retention',
    'privacy.dataRetention.content': 'Our data retention policy is as follows:',
    'privacy.dataRetention.sessionData': '• Session data: Automatically deleted after 30 days',
    'privacy.dataRetention.logData': '• Log data: Retained for 90 days for security analysis',
    'privacy.dataRetention.userContent': '• User content: Can be deleted at any time upon user request',
    'privacy.dataSecurity.title': '4. Data Security',
    'privacy.dataSecurity.content': 'We employ multiple security measures to protect your data:',
    'privacy.dataSecurity.encryption': '• Use HTTPS encryption for all data transmission',
    'privacy.dataSecurity.accessControl': '• Implement strict access control and permission management',
    'privacy.dataSecurity.monitoring': '• 24/7 security monitoring and anomaly detection',
    'privacy.dataSecurity.updates': '• Regular security updates and system patches',
    'privacy.userRights.title': '5. User Rights',
    'privacy.userRights.content': 'You have the following rights:',
    'privacy.userRights.access': '• Query information we have collected about you',
    'privacy.userRights.correction': '• Request correction of inaccurate personal information',
    'privacy.userRights.deletion': '• Request deletion of your personal data',
    'privacy.userRights.portability': '• Request export of your data',
    'privacy.cookies.title': '6. Cookie Usage',
    'privacy.cookies.content': 'We use cookies to improve your browsing experience. For detailed information, please refer to our Cookie Policy.',
    'privacy.changes.title': '7. Policy Changes',
    'privacy.changes.content': 'We may update this privacy policy from time to time. Major changes will be announced through website notifications.',
    'privacy.contact.title': '8. Contact Us',
    'privacy.contact.content': 'If you have any questions about this privacy policy or need to exercise your rights, please contact us through the website contact feature.',
    // Privacy badges and labels
    'privacy.important': 'Important',
    'privacy.days30': '30 days',
    'privacy.days90': '90 days',
    'privacy.anytime': 'Anytime',
    // Common
    'common.backToHome': 'Back to Home',
    'common.lastUpdated': 'Last updated',
    // Terms agreement
    'auth.termsAgreement': 'By signing up, you agree to our Terms of Service and Privacy Policy',
    'auth.termsAgreementShort': 'By signing up, you agree to our',
    'auth.and': 'and',
    'auth.termsCheckbox': 'I have read and agree to the',
    'auth.termsOfService': 'Terms of Service',
    'auth.privacyPolicy': 'Privacy Policy',
    'auth.mustAgreeTerms': 'You must agree to the Terms of Service and Privacy Policy to continue',
    // Contact Page
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Have any questions or suggestions? We\'d love to hear from you',
    'contact.methods': 'Contact Methods',
    'contact.email': 'Email',
    'contact.github': 'GitHub',
    'contact.developer': 'Developer',
    'contact.privacy': 'Privacy Protection',
    'contact.privacyMessage': 'We promise to protect your privacy. Your contact information will only be used to reply to your inquiries and will not be shared with third parties.',
    'contact.faq': 'Frequently Asked Questions',
    'contact.faqReport': 'How to report inappropriate content?',
    'contact.faqReportAnswer': 'Please report any content that violates community guidelines by sending an email to <a href="mailto:support@lingubible.com" class="underline hover:no-underline">support@lingubible.com</a>.',
    'contact.faqDelete': 'How to delete my comments?',
    'contact.faqDeleteAnswer': 'Please contact us with relevant information and we will assist you.',
    'contact.faqTechnical': 'Technical Issue Reports',
    'contact.faqTechnicalAnswer': 'Encountered website technical issues? Please describe the problem in detail and send it to us.',
    'contact.sendMessage': 'Send Message',
    'contact.name': 'Name',
    'contact.namePlaceholder': 'Please enter your name',
    'contact.emailPlaceholder': 'Please enter your email',
    'contact.subject': 'Subject',
    'contact.subjectPlaceholder': 'Please enter message subject',
    'contact.message': 'Message Content',
    'contact.messagePlaceholder': 'Please describe your questions or suggestions in detail...',
    'contact.sending': 'Sending...',
    'contact.send': 'Send Message',
    'contact.successMessage': 'Message sent successfully! We will reply to you as soon as possible.',
    'contact.errorMessage': 'Send failed, please try again later or send email directly to support@lingubible.com',
    // User Settings Page
    'settings.title': 'User Settings',
    'settings.subtitle': 'Manage your personal information and preferences',
    'settings.backToHome': 'Back to Home',
    'settings.profile': 'Profile',
    'settings.profileDescription': 'Update your personal information',
    'settings.email': 'Email',
    'settings.emailReadOnly': 'Email address cannot be modified',
    'settings.username': 'Username',
    'settings.usernamePlaceholder': 'Enter your username (2-10 characters, can be empty)',
    'settings.usernameAvailable': 'Username available',
    'settings.usernameRules': 'Username Rules:',
    'settings.usernameLength': '• Length: 2-10 characters (can be empty)',
    'settings.usernameSupported': '• Supports: Chinese, English, numbers, symbols, spaces',
    'settings.usernameEmpty': '• When empty, email prefix will be displayed as username',
    'settings.usernameDisplay': '• Username will be displayed in profile and comments',
    'settings.saving': 'Saving...',
    'settings.saveChanges': 'Save Changes',
    'settings.reset': 'Reset',
    'settings.saveSuccess': '✅ Save Successful',
    'settings.saveFailed': 'Save Failed',
    'settings.usernameUpdated': 'Username updated to: {username}',
    'settings.usernameCleared': 'Username cleared, email prefix will be displayed',
    'settings.updateError': 'Error occurred while updating username, please try again later',
    'settings.loginRequired': 'Please log in to access user settings',
    'settings.login': 'Log In',
    // Danger Zone
    'settings.dangerZone.title': 'Danger Zone',
    'settings.dangerZone.description': 'Account management actions',
    'settings.dangerZone.warning': 'This action will temporarily disable your account. Please proceed with caution.',
    'settings.dangerZone.deleteAccount': 'Disable Account',
    'settings.dangerZone.confirmDelete': 'Confirm Account Disabling',
    'settings.dangerZone.confirmDeleteDesc': 'This action will temporarily disable your account. You will not be able to log in until you re-enable it.',
    'settings.dangerZone.irreversibleWarning': 'Your account will be temporarily disabled. You can re-enable it by logging in again.',
    'settings.dangerZone.confirmEmailLabel': 'Type your email address to confirm',
    'settings.dangerZone.confirmEmailDesc': 'Please type your email address exactly as shown above to confirm disabling.',
    'settings.dangerZone.cancel': 'Cancel',
    'settings.dangerZone.confirmDeleteButton': 'Disable My Account',
    'settings.dangerZone.deleting': 'Disabling...',
    'settings.dangerZone.completeDeleteInfo': 'If you want to completely delete your account, please send an email to contact@lingubible.com',
    'settings.dangerZone.reEnableInfo': 'To re-enable your disabled account, simply log in again with your credentials.',
    'settings.deleteAccount.emailMismatch': 'Email Mismatch',
    'settings.deleteAccount.emailMismatchDesc': 'The email address you entered does not match your account email.',
    'settings.deleteAccount.success': 'Account Disabled',
    'settings.deleteAccount.successDesc': 'Your account has been temporarily disabled. You can re-enable it by logging in again.',
    'settings.deleteAccount.failed': 'Disabling Failed',
    'settings.deleteAccount.failedDesc': 'Failed to disable account, please try again later.',
    'auth.showPassword': 'Show password',
    'auth.hidePassword': 'Hide password',
  },
  'zh-TW': {
    // Site metadata
    'site.name': 'LingUBible',
    'site.title': 'LingUBible - 課程與講師評價平台',
    'site.description': '真實可靠的Reg科聖經，幫助同學們作出明智的選擇',
    'hero.title': '歡迎來到',
    'hero.subtitle': '真實可靠的Reg科聖經，幫助同學們作出明智的選擇',
    'hero.action': '評論',
    'hero.actions': ['發表評價', '投票', '提出問題', '回答問題'],
    'hero.getStarted': '開始使用',
    'hero.comeHereTo': '來這裡',
    'nav.home': '首頁',
    'nav.courses': '課程',
    'nav.lecturers': '講師',
    'nav.about': '關於',
    'nav.signIn': '登入',
    'stats.totalCourses': '總課程數',
    'stats.lecturers': '講師',
    'stats.reviews': '評價',
    'stats.activeStudents': '活躍學生',
    'stats.thisMonth': '本月',
    'tabs.popularCourses': '熱門課程',
    'tabs.topLecturers': '頂級講師',
    'footer.builtWith': '由 ansonlo.dev 用 💝 製作',
    'footer.disclaimer': '本網站與嶺南大學沒有任何關係',
    // Footer additional
    'footer.builtWithTools': '由開源工具構建，作者',
    'footer.beta': 'BETA',
    'footer.version': '版本 0.0.1',
    'footer.contact': '聯絡',
    'footer.terms': '條款',
    'footer.privacy': '隱私',
    // Auth Modal
    'auth.signIn': '登入',
    'auth.signUp': '註冊',
    'auth.email': '電子郵件',
    'auth.password': '密碼',
    'auth.confirmPassword': '確認密碼',
    'auth.enterEmail': '請輸入您的電子郵件',
    'auth.enterPassword': '請輸入您的密碼',
    'auth.confirmPasswordPlaceholder': '請確認您的密碼',
    'auth.alreadyHaveAccount': '已有帳戶？立即登入',
    'auth.dontHaveAccount': '沒有帳戶？立即註冊',
    'auth.passwordMismatch': '兩次密碼不一致',
    'auth.passwordMatch': '兩次密碼一致',
    'auth.rememberMe': '記住我',
    'auth.authFailed': '認證失敗，請檢查資料',
    'auth.pleaseVerifyStudentEmail': '請先驗證您的嶺南人電子郵件地址',
    'auth.passwordNotSecure': '密碼不符合安全要求，請檢查密碼強度指示器',
    'auth.passwordTooShort': '密碼必須在 8 到 256 個字符之間',
    'auth.rateLimitExceeded': '請求過於頻繁，請稍後再試',
    'auth.secureConnection': '您的憑證將會被加密並在安全的連接中發送。',
    'auth.schoolPasswordReminder': '請不要使用與您的學校郵件帳戶相同的密碼。為了保護您的帳戶安全，建議為每個服務使用不同的密碼。',
    'auth.forgotPassword': '忘記密碼？',
    'auth.resetPassword': '重置密碼',
    'auth.sendResetEmail': '發送重置郵件',
    'auth.resetEmailSent': '密碼重置郵件已發送到您的電子郵件地址。',
    'auth.studentVerificationSuccess': '嶺南人郵件驗證成功！您現在可以設置密碼以完成註冊。',
    'auth.backToLogin': '返回登入',
    'auth.backToHome': '返回首頁',
    'auth.noAccount': '沒有帳戶？',
    'auth.haveAccount': '已有帳戶？',
    'auth.contact': '聯絡',
    'auth.terms': '條款',
    'auth.privacy': '隱私',
    'auth.help': '幫助中心',
    // Auth page titles and descriptions
    'auth.welcomeBack': '歡迎回來',
    'auth.createStudentAccount': '創建您的嶺南人帳戶',
    'auth.fillInfoToCreate': '填寫以下資訊來創建您的嶺南人帳戶',
    'auth.studentInfoVerification': '嶺南人資訊驗證',
    'auth.passwordSetup': '密碼設定',
    'auth.usernameSetup': '用戶名設定',
    'auth.username': '用戶名',
    'auth.usernamePlaceholder': '請輸入您的用戶名 (2-10字符)',
    'auth.usernameAvailable': '用戶名可用',
    'auth.usernameRules': '用戶名規則：',
    'auth.usernameLength': '• 長度：2-10 個字符',
    'auth.usernameSupported': '• 支持：中文、英文、數字、符號、空格',
    'auth.usernameDisplay': '• 用戶名將顯示在個人資料和評論中',
    'auth.usernameModifiable': '• 可在註冊後於設置中修改',
    'auth.usernameSuggestion': '建議用戶名：',
    'auth.useSuggestion': '使用',
    'auth.enterAccountInfo': '輸入您的帳戶資訊來登入',
    'auth.resetYourPassword': '重置您的密碼',
    'auth.signOut': '登出',
    // Toast messages
    'toast.loginSuccess': '登入成功！',
    'toast.welcomeBack': '歡迎回來，{username}！',
    'toast.registerSuccess': '註冊成功！',
    'toast.welcomeToApp': '歡迎來到 LingUBible，{username}！',
    'toast.logoutSuccess': '登出成功',
    'toast.goodbye': '再見，{username}！期待您的下次造訪。',
    // Search
    'search.placeholder': '搜尋課程、講師...',
    // Buttons
    'button.viewAll': '查看全部',
    'button.review': '評價',
    'button.viewDetails': '查看詳情',
    'button.viewProfile': '查看檔案',
    // Course/Lecturer Cards
    'card.reviews': '評價',
    'card.students': '學生',
    'card.courses': '課程',
    'card.specialties': '專業領域',
    'card.more': '更多',
    'card.prof': '教授',
    // Difficulty levels
    'difficulty.easy': '簡單',
    'difficulty.medium': '中等',
    'difficulty.hard': '困難',
    // Departments
    'department.computerScience': '計算機科學',
    'department.mathematics': '數學',
    'department.english': '英語',
    // Specialties
    'specialty.programming': '程式設計',
    'specialty.dataStructures': '資料結構',
    'specialty.algorithms': '演算法',
    'specialty.machineLearning': '機器學習',
    'specialty.calculus': '微積分',
    'specialty.linearAlgebra': '線性代數',
    'specialty.statistics': '統計學',
    'specialty.literature': '文學',
    'specialty.creativeWriting': '創意寫作',
    'specialty.poetry': '詩歌',
    'specialty.drama': '戲劇',
    // Sample course titles
    'course.introCS': '計算機科學導論',
    'course.advancedMath': '高等數學',
    'course.englishLit': '英國文學',
    // Sidebar
    'sidebar.myReviews': '我的評價',
    'sidebar.trending': '熱門',
    'sidebar.settings': '設置',
    // Password Security
    'password.strength': '密碼強度',
    'password.requirements': '密碼要求：',
    'password.length': '密碼長度為 8-40 個字符',
    'password.uppercase': '包含至少 1 個大寫字母',
    'password.lowercase': '包含至少 1 個小寫字母',
    'password.special': '包含至少 1 個特殊符號 (!@#$%^&*等)',
    'password.number': '包含至少 1 個數字',
    'password.notCommon': '不是常用密碼',
    'password.notLeaked': '不匹配已知洩露密碼模式',
    'password.notSimilarToEmail': '不應與學校郵件地址相似',
    'password.lengthSuggestion': '建議使用 12 個字符以上以提高安全性',
    'password.weak': '弱',
    'password.fair': '一般',
    'password.good': '良好',
    'password.strong': '強',
    'password.securityReminder': '安全提醒：',
    'password.schoolEmailWarning': '請不要使用與您的學校郵件帳戶相同的密碼。為了保護您的帳戶安全，建議為每個服務使用不同的密碼。',
    'password.commonPasswordDanger': '危險：',
    'password.commonPasswordMessage': '您使用的是常見密碼，這種密碼很容易被破解。請選擇一個更安全的密碼。',
    'password.leakedPasswordRisk': '高風險：',
    'password.leakedPasswordMessage': '此密碼匹配已知的洩露密碼模式，極易被攻擊者猜測。請立即更換為更安全的密碼。',
    // Forgot password page
    'auth.emailSent': '郵件已發送',
    'auth.checkYourEmail': '請檢查您的郵箱',
    'auth.resetLinkSent': '我們已向',
    'auth.resetLinkSentComplete': '發送了密碼重置連結。',
    'auth.checkSpamFolder': '如果您沒有收到郵件，請檢查垃圾郵件資料夾。',
    'auth.enterSchoolEmail': '輸入您的學校郵件地址，我們將發送重置連結給您',
    'auth.schoolEmailPlaceholder': 'student@ln.hk 或 student@ln.edu.hk',
    'auth.useSchoolEmail': '請使用您的學校郵件地址（@ln.hk 或 @ln.edu.hk）',
    'auth.sendResetFailed': '發送重置郵件失敗，請稍後再試',
    'auth.sending': '發送中...',
    'auth.securityReminder': '安全提醒',
    'auth.resetLinkExpiry': '重置連結將在 24 小時後過期',
    'auth.resetLinkWillExpire': '重設連結將在 24 小時後過期',
    'auth.checkEmailInbox': '請檢查您的信箱：',
    'auth.canRetryReset': '您可以重新嘗試發送重設郵件',
    'auth.resendReset': '重新發送',
    'auth.sendResetLink': '發送重設連結',
    'auth.studentEmailAddress': '嶺南人郵件地址',
    'auth.resetPasswordDescription': '輸入您的嶺南人郵件地址，我們將發送重設密碼的連結給您',
    'auth.emailNotRegistered': '此郵件地址尚未註冊。請先註冊或檢查您的郵件地址。',
    'auth.checkingEmailExists': '檢查郵件是否已註冊...',
    'auth.emailRegistered': '郵件地址已註冊',
    'auth.invalidCredentials': '郵件地址或密碼錯誤，請檢查後重試',
    'auth.registrationFailed': '註冊失敗，請檢查資料後重試',
    // Processing
    'auth.processing': '處理中...',
    // Email placeholder
    'auth.emailPlaceholder': 'student@ln.hk 或 student@ln.edu.hk',
    // Email validation
    'auth.invalidStudentEmail': '此郵件地址不是有效的嶺南人郵件地址。請使用有效的 @ln.hk 或 @ln.edu.hk 郵件地址。',
    // Email checking status
    'auth.checkingEmail': '檢查郵件是否可用...',
    'auth.checkingAccount': '檢查帳戶...',
    'auth.emailAvailable': '郵件地址可用',
    // Student verification
    'verification.title': '嶺南人郵件驗證',
    'verification.sendCode': '發送驗證碼',
    'verification.onlyStudentEmails': '只有 @ln.hk 或 @ln.edu.hk 郵件地址的嶺南人才能註冊',
    'verification.codeExpiry': '驗證碼有效期為 10 分鐘',
    'verification.maxAttempts': '最多可嘗試驗證 3 次',
    'verification.resendAfter': '後可重新發送',
    'verification.enterCode': '請輸入 6 位數驗證碼',
    'verification.verifying': '驗證中...',
    'verification.verify': '驗證',
    'verification.resend': '重新',
    'verification.sendingCode': '正在發送驗證碼...',
    'verification.codeSent': '驗證碼已發送到您的郵件地址，請檢查您的信箱',
    'verification.verifyFailed': '驗證失敗',
    // Email reminder
    'email.reminder.title': '📧 郵件發送提醒',
    'email.reminder.checkSpam': '如果您沒有收到郵件，請檢查垃圾郵件資料夾',
    'email.reminder.whitelist': '建議將 noreply@lingubible.com 加入您的郵件白名單',
    'email.reminder.deliveryTime': '郵件發送可能需要 1-2 分鐘',
    'email.reminder.contactSupport': '如果 5 分鐘後仍未收到郵件，請聯繫技術支援',
    // Password strength
    'password.strengthLabel': '強度：',
    // Swipe hint
    'swipe.hint': '在屏幕任意位置向右滑動展開選單',
    'swipe.dismissHint': '滾動頁面關閉提示',
    // Cookie consent
    'cookie.title': 'Cookie 使用同意',
    'cookie.description': '本網站使用 Cookie 來確保您獲得最佳的瀏覽體驗。',
    'cookie.accept': '我了解',
    'cookie.learnMore': '了解更多',
    'cookie.decline': '拒絕',
    'cookie.close': '關閉',
    // Cookie policy details
    'cookie.policy.title': '我們如何使用 Cookie',
    'cookie.policy.intro': '我們使用 Cookie 來提升您的瀏覽體驗並改善我們的服務。具體如下：',
    'cookie.policy.essential.title': '必要 Cookie',
    'cookie.policy.essential.desc': '這些 Cookie 是網站正常運作所必需的。它們啟用基本功能，如頁面導航、用戶認證和安全性。',
    'cookie.policy.functional.title': '功能性 Cookie',
    'cookie.policy.functional.desc': '這些 Cookie 會記住您的偏好設定（如語言設定、主題和側邊欄狀態），以提供個人化體驗。',
    'cookie.policy.analytics.title': '分析 Cookie',
    'cookie.policy.analytics.desc': '我們使用這些 Cookie 來了解訪客如何與我們的網站互動，幫助我們改善性能和用戶體驗。',
    'cookie.policy.types': '我們使用的 Cookie 類型：',
    'cookie.policy.type1': '• 身份驗證 Cookie，保持您的登入狀態',
    'cookie.policy.type2': '• 語言偏好 Cookie',
    'cookie.policy.type3': '• 主題和佈局偏好 Cookie',
    'cookie.policy.type4': '• 匿名使用分析',
    'cookie.policy.retention': 'Cookie 保存期限',
    'cookie.policy.retention.desc': '大多數 Cookie 會保存最多 1 年，而會話 Cookie 會在您關閉瀏覽器時刪除。',
    'cookie.policy.control': '您的控制權',
    'cookie.policy.control.desc': '您可以通過瀏覽器設定來控制 Cookie。但是，禁用某些 Cookie 可能會影響網站功能。',
    'cookie.policy.contact': '如果您對我們的 Cookie 政策有疑問，請聯繫我們。',
    // PWA Install
    'pwa.installAvailable': '應用程式可安裝',
    'pwa.installDescription': '安裝 LingUBible 獲得更好的使用體驗',
    'pwa.installBenefits': '更快載入、離線存取和原生應用體驗',
    'pwa.install': '安裝',
    'pwa.installApp': '安裝應用',
    'pwa.howToInstall': '安裝方法',
    'pwa.notNow': '稍後再說',
    'pwa.dismiss': '關閉',
    'pwa.gotIt': '我知道了',
    'pwa.installSuccess': '應用安裝成功！',
    'pwa.installFailed': '安裝失敗，請重試。',
    'pwa.alreadyInstalled': '應用已安裝',
    'pwa.updateAvailable': '應用更新可用',
    'pwa.updateNow': '立即更新',
    'pwa.updateLater': '稍後更新',
    // User Stats
    'stats.onlineUsers': '在線用戶',
    'stats.totalRegistered': '總註冊數',
    'stats.todayLogins': '今日登入',
    'stats.thisMonthLogins': '本月登入',
    'stats.usersOnline': '位用戶在線',
    'stats.loading': '載入中...',
    // OpenStatus
    'status.operational': 'Operational',
    'status.degraded': 'Degraded',
    'status.down': 'Down',
    'status.checking': 'Checking',
    'status.poweredBy': 'Powered by OpenStatus',
    // Avatar
    'avatar.customize': '自定義頭像',
    'avatar.combinations': '種組合',
    'avatar.preview': '預覽效果',
    'avatar.randomize': '隨機生成',
    'avatar.save': '保存頭像',
    'avatar.saving': '保存中...',
    'avatar.resetToDefault': '重置為默認',
    'avatar.animals': '動物',
    'avatar.backgrounds': '背景',
    'avatar.totalStats': '共有 {animals} 種動物 × {backgrounds} 種背景 = {total} 種組合',
    'avatar.saveSuccess': '頭像已保存',
    'avatar.saveSuccessDesc': '您的自定義頭像已成功保存到雲端',
    'avatar.saveFailed': '保存失敗',
    'avatar.saveFailedDesc': '無法保存頭像，請稍後再試',
    'avatar.resetSuccess': '頭像已重置',
    'avatar.resetSuccessDesc': '已恢復為系統默認頭像',
    'avatar.deleteFailed': '刪除失敗',
    'avatar.deleteFailedDesc': '無法刪除頭像，請稍後再試',
    'avatar.saveError': '保存失敗，請稍後再試',
    // Background colors
    'background.sunset': '夕陽',
    'background.peach': '蜜桃',
    'background.coral': '珊瑚',
    'background.rose': '玫瑰',
    'background.ocean': '海洋',
    'background.sky': '天空',
    'background.mint': '薄荷',
    'background.forest': '森林',
    'background.lavender': '薰衣草',
    'background.grape': '葡萄',
    'background.plum': '梅子',
    'background.cloud': '雲朵',
    'background.stone': '石頭',
    'background.warm': '暖陽',
    'background.rainbow': '彩虹',
    'background.aurora': '極光',
    'background.cosmic': '宇宙',
    'background.tropical': '熱帶',
    'background.fire': '火焰',
    'background.ice': '冰雪',
    // Terms of Service
    'terms.title': '使用條款',
    'terms.lastUpdated': '最後更新：2025年6月5日',
    'terms.welcome': '歡迎使用 LingUBible',
    'terms.acceptance.title': '1. 接受條款',
    'terms.acceptance.content': '使用本網站即表示您同意遵守這些使用條款。如果您不同意這些條款，請不要使用本服務。',
    'terms.conduct.title': '2. 用戶行為準則',
    'terms.conduct.content': '為了維護良好的社區環境，用戶必須遵守以下行為準則：',
    'terms.conduct.noSwearing': '• 禁止使用粗言穢語或不當言論',
    'terms.conduct.noPersonalAttacks': '• 禁止人身攻擊或針對個人的惡意言論',
    'terms.conduct.noSpam': '• 禁止發送垃圾信息或重複無意義的內容',
    'terms.conduct.respectful': '• 保持尊重和建設性的討論態度',
    'terms.conduct.violation': '違反上述準則可能導致帳戶被暫停或永久封禁',
    'terms.moderation.title': '3. 內容管理',
    'terms.moderation.content': '我們保留審核和管理平台內容的權利：',
    'terms.moderation.removal': '• 不當評論將被刪除，且不會事先通知',
    'terms.moderation.standards': '• 我們致力於維護高質量的討論環境',
    'terms.moderation.discretion': '• 管理決定將基於社區準則和管理團隊的判斷',
    'terms.privacy.title': '4. 隱私保護',
    'terms.privacy.content': '我們承諾保護您的隱私：',
    'terms.privacy.anonymity': '• 評論者的身份將被嚴格保密',
    'terms.privacy.noDisclosure': '• 我們不會向任何第三方披露用戶身份信息',
    'terms.privacy.dataCollection': '• 詳細的數據收集政策請參閱隱私政策',
    'terms.changes.title': '5. 條款變更',
    'terms.changes.content': '我們可能會不時更新這些條款。重大變更將通過網站公告通知用戶。',
    'terms.contact.title': '8. 聯繫我們',
    'terms.contact.content': '如果您對這些條款有任何疑問，請通過網站聯繫功能與我們聯繫。',
    'terms.username.title': '6. 用戶名政策',
    'terms.username.content': '用戶需對其選擇的用戶名負責：',
    'terms.username.offensive': '• 冒犯性、不當或誤導性的用戶名可能會在不通知的情況下被更改',
    'terms.username.discretion': '• 用戶名更改由管理團隊自行決定',
    'terms.username.responsibility': '• 用戶有責任確保其用戶名符合社區標準',
    'terms.content.title': '7. 內容政策',
    'terms.content.content': '為了維護專注且相關的討論環境：',
    'terms.content.noPolitics': '• 不允許政治討論',
    'terms.content.noReligion': '• 不允許宗教討論',
    'terms.content.noUnrelated': '• 不允許與網站目的無關的內容',
    'terms.content.removal': '無關或不當內容將在不通知的情況下被刪除',
    'terms.content.focus': '• 請將討論重點放在課程和講師評價上',
    // Privacy Policy
    'privacy.title': '隱私政策',
    'privacy.lastUpdated': '最後更新：2025年6月5日',
    'privacy.intro': '本隱私政策說明我們如何收集、使用和保護您的個人信息。',
    'privacy.dataCollection.title': '1. 數據收集',
    'privacy.dataCollection.content': '為了提供更好的服務和維護平台安全，我們會收集以下信息：',
    'privacy.dataCollection.sessionTime': '會話時間：用於分析用戶活躍度和改善服務質量',
    'privacy.dataCollection.ipAddress': 'IP 地址：用於安全監控和防止濫用行為',
    'privacy.dataCollection.userAgent': '瀏覽器信息：用於優化網站兼容性和用戶體驗',
    'privacy.dataCollection.purpose': '收集這些信息的目的是為了：',
    'privacy.dataCollection.security': '• 維護平台安全，防止惡意攻擊和濫用',
    'privacy.dataCollection.analytics': '• 分析用戶行為，改善服務質量',
    'privacy.dataCollection.technical': '• 提供技術支援和故障排除',
    'privacy.dataCollection.compliance': '• 遵守法律法規要求',
    'privacy.anonymity.title': '2. 匿名性保護',
    'privacy.anonymity.content': '我們高度重視用戶的匿名性：',
    'privacy.anonymity.strictConfidentiality': '評論者的身份信息將被嚴格保密',
    'privacy.anonymity.noDisclosure': '我們承諾不會向任何個人、組織或第三方披露用戶的真實身份',
    'privacy.anonymity.internalAccess': '只有授權的技術人員在必要時才能訪問用戶數據，且僅用於技術維護',
    'privacy.anonymity.legalProtection': '除非法律明確要求，否則我們不會主動披露用戶信息',
    'privacy.dataRetention.title': '3. 數據保留',
    'privacy.dataRetention.content': '我們的數據保留政策如下：',
    'privacy.dataRetention.sessionData': '• 會話數據：保留 30 天後自動刪除',
    'privacy.dataRetention.logData': '• 日誌數據：保留 90 天用於安全分析',
    'privacy.dataRetention.userContent': '• 用戶內容：根據用戶要求可隨時刪除',
    'privacy.dataSecurity.title': '4. 數據安全',
    'privacy.dataSecurity.content': '我們採用多重安全措施保護您的數據：',
    'privacy.dataSecurity.encryption': '• 使用 HTTPS 加密傳輸所有數據',
    'privacy.dataSecurity.accessControl': '• 實施嚴格的訪問控制和權限管理',
    'privacy.dataSecurity.monitoring': '• 24/7 安全監控和異常檢測',
    'privacy.dataSecurity.updates': '• 定期更新安全措施和系統補丁',
    'privacy.userRights.title': '5. 用戶權利',
    'privacy.userRights.content': '您擁有以下權利：',
    'privacy.userRights.access': '• 查詢我們收集的關於您的信息',
    'privacy.userRights.correction': '• 要求更正不準確的個人信息',
    'privacy.userRights.deletion': '• 要求刪除您的個人數據',
    'privacy.userRights.portability': '• 要求導出您的數據',
    'privacy.cookies.title': '6. Cookie 使用',
    'privacy.cookies.content': '我們使用 Cookie 來改善您的瀏覽體驗。詳細信息請參閱我們的 Cookie 政策。',
    'privacy.changes.title': '7. 政策變更',
    'privacy.changes.content': '我們可能會不時更新此隱私政策。重大變更將通過網站公告通知用戶。',
    'privacy.contact.title': '8. 聯繫我們',
    'privacy.contact.content': '如果您對此隱私政策有任何疑問或需要行使您的權利，請通過網站聯繫功能與我們聯繫。',
    // Privacy badges and labels
    'privacy.important': '重要',
    'privacy.days30': '30 天',
    'privacy.days90': '90 天',
    'privacy.anytime': '隨時',
    // Common
    'common.backToHome': '返回首頁',
    'common.lastUpdated': '最後更新',
    // Terms agreement
    'auth.termsAgreement': '註冊即表示您同意我們的使用條款和隱私政策',
    'auth.termsAgreementShort': '註冊即表示您同意我們的',
    'auth.and': '和',
    'auth.termsCheckbox': '我已閱讀並同意',
    'auth.termsOfService': '使用條款',
    'auth.privacyPolicy': '隱私政策',
    'auth.mustAgreeTerms': '您必須同意使用條款和隱私政策才能繼續',
    // Contact Page
    'contact.title': '聯繫我們',
    'contact.subtitle': '有任何問題或建議？我們很樂意聽取您的意見',
    'contact.methods': '聯繫方式',
    'contact.email': '電子郵件',
    'contact.github': 'GitHub',
    'contact.developer': '開發者',
    'contact.privacy': '隱私保護',
    'contact.privacyMessage': '我們承諾保護您的隱私。您的聯繫信息僅用於回復您的查詢，不會與第三方分享。',
    'contact.faq': '常見問題',
    'contact.faqReport': '如何報告不當內容？',
    'contact.faqReportAnswer': '請發送電子郵件至 <a href="mailto:support@lingubible.com" class="underline hover:no-underline">support@lingubible.com</a> 向我們報告任何違反社區準則的內容。',
    'contact.faqDelete': '如何刪除我的評論？',
    'contact.faqDeleteAnswer': '請聯繫我們並提供相關信息，我們會協助您處理。',
    'contact.faqTechnical': '技術問題回報',
    'contact.faqTechnicalAnswer': '遇到網站技術問題？請詳細描述問題並發送給我們。',
    'contact.sendMessage': '發送消息',
    'contact.name': '姓名',
    'contact.namePlaceholder': '請輸入您的姓名',
    'contact.emailPlaceholder': '請輸入您的電子郵件',
    'contact.subject': '主題',
    'contact.subjectPlaceholder': '請輸入消息主題',
    'contact.message': '消息內容',
    'contact.messagePlaceholder': '請詳細描述您的問題或建議...',
    'contact.sending': '發送中...',
    'contact.send': '發送消息',
    'contact.successMessage': '消息發送成功！我們會盡快回復您。',
    'contact.errorMessage': '發送失敗，請稍後再試或直接發送郵件至 support@lingubible.com',
    // User Settings Page
    'settings.title': '用戶設定',
    'settings.subtitle': '管理您的個人資料和偏好設定',
    'settings.backToHome': '返回首頁',
    'settings.profile': '個人資料',
    'settings.profileDescription': '更新您的個人資料信息',
    'settings.email': '電子郵件',
    'settings.emailReadOnly': '電子郵件地址無法修改',
    'settings.username': '用戶名',
    'settings.usernamePlaceholder': '輸入您的用戶名 (2-10字符，可留空)',
    'settings.usernameAvailable': '用戶名可用',
    'settings.usernameRules': '用戶名規則：',
    'settings.usernameLength': '• 長度：2-10 個字符（可留空）',
    'settings.usernameSupported': '• 支持：中文、英文、數字、符號、空格',
    'settings.usernameEmpty': '• 留空時將顯示郵箱前綴作為用戶名',
    'settings.usernameDisplay': '• 用戶名將顯示在個人資料和評論中',
    'settings.saving': '保存中...',
    'settings.saveChanges': '保存更改',
    'settings.reset': '重置',
    'settings.saveSuccess': '✅ 保存成功',
    'settings.saveFailed': '保存失敗',
    'settings.usernameUpdated': '用戶名已更新為：{username}',
    'settings.usernameCleared': '用戶名已清空，將顯示郵箱前綴',
    'settings.updateError': '更新用戶名時發生錯誤，請稍後再試',
    'settings.loginRequired': '請先登入以訪問用戶設定',
    'settings.login': '登入',
    // Danger Zone
    'settings.dangerZone.title': '危險區',
    'settings.dangerZone.description': '帳戶管理操作',
    'settings.dangerZone.warning': '此操作將暫時禁用您的帳戶。請謹慎進行。',
    'settings.dangerZone.deleteAccount': '禁用帳戶',
    'settings.dangerZone.confirmDelete': '確認帳戶禁用',
    'settings.dangerZone.confirmDeleteDesc': '此操作將暫時禁用您的帳戶。您將無法登入，直到重新啟用為止。',
    'settings.dangerZone.irreversibleWarning': '您的帳戶將被暫時禁用。您可以通過重新登入來重新啟用。',
    'settings.dangerZone.confirmEmailLabel': '輸入您的電子郵件地址以確認',
    'settings.dangerZone.confirmEmailDesc': '請輸入您的電子郵件地址完全相同以確認禁用。',
    'settings.dangerZone.cancel': '取消',
    'settings.dangerZone.confirmDeleteButton': '禁用我的帳戶',
    'settings.dangerZone.deleting': '禁用中...',
    'settings.dangerZone.completeDeleteInfo': '如需完全刪除帳戶，請發送郵件至 contact@lingubible.com',
    'settings.dangerZone.reEnableInfo': '如需重新啟用被禁用的帳戶，只需使用您的憑證重新登入即可。',
    'settings.deleteAccount.emailMismatch': '電子郵件不匹配',
    'settings.deleteAccount.emailMismatchDesc': '您輸入的電子郵件地址與您的帳戶電子郵件地址不匹配。',
    'settings.deleteAccount.success': '帳戶已禁用',
    'settings.deleteAccount.successDesc': '您的帳戶已暫時禁用。您可以通過重新登入來重新啟用。',
    'settings.deleteAccount.failed': '禁用失敗',
    'settings.deleteAccount.failedDesc': '禁用帳戶失敗，請稍後再試。',
    'auth.showPassword': '顯示密碼',
    'auth.hidePassword': '隱藏密碼',
  },
  'zh-CN': {
    // Site metadata
    'site.name': 'LingUBible',
    'site.title': 'LingUBible - 课程与讲师评价平台',
    'site.description': '您诚实的课程和讲师评价平台，帮助同学们做出明智的决定',
    'hero.title': '欢迎来到',
    'hero.subtitle': '您诚实的课程和讲师评价平台，帮助同学们做出明智的决定',
    'hero.action': '评论',
    'hero.actions': ['评论', '投票', '提出问题', '回答问题'],
    'hero.getStarted': '开始使用',
    'hero.comeHereTo': '来这里',
    'nav.home': '首页',
    'nav.courses': '课程',
    'nav.lecturers': '讲师',
    'nav.about': '关于',
    'nav.signIn': '登录',
    'stats.totalCourses': '总课程数',
    'stats.lecturers': '讲师',
    'stats.reviews': '评价',
    'stats.activeStudents': '活跃学生',
    'stats.thisMonth': '本月',
    'tabs.popularCourses': '热门课程',
    'tabs.topLecturers': '顶级讲师',
    'footer.builtWith': '由 ansonlo.dev 用 💝 制作',
    'footer.disclaimer': '本网站与岭南大学没有关系',
    // Footer additional
    'footer.builtWithTools': '由开源工具构建，作者',
    'footer.beta': 'BETA',
    'footer.version': '版本 0.0.1',
    'footer.contact': '联系',
    'footer.terms': '条款',
    'footer.privacy': '隐私',
    // Auth Modal
    'auth.signIn': '登录',
    'auth.signUp': '注册',
    'auth.email': '电子邮箱',
    'auth.password': '密码',
    'auth.confirmPassword': '确认密码',
    'auth.enterEmail': '请输入您的电子邮箱',
    'auth.enterPassword': '请输入您的密码',
    'auth.confirmPasswordPlaceholder': '请确认您的密码',
    'auth.alreadyHaveAccount': '已有账户？立即登录',
    'auth.dontHaveAccount': '没有账户？立即注册',
    'auth.passwordMismatch': '两次密码不一致',
    'auth.passwordMatch': '两次密码一致',
    'auth.rememberMe': '记住我',
    'auth.authFailed': '认证失败，请检查资料',
    'auth.pleaseVerifyStudentEmail': '请先验证您的岭南人电子邮件地址',
    'auth.passwordNotSecure': '密码不符合安全要求，请检查密码强度指示器',
    'auth.passwordTooShort': '密码必须在 8 到 256 个字符之间',
    'auth.rateLimitExceeded': '请求过于频繁，请稍后再试',
    'auth.secureConnection': '您的凭证将会被加密并在安全的连接中发送。',
    'auth.schoolPasswordReminder': '请不要使用与您的学校邮件账户相同的密码。为了保护您的账户安全，建议为每个服务使用不同的密码。',
    'auth.forgotPassword': '忘记密码？',
    'auth.resetPassword': '重置密码',
    'auth.sendResetEmail': '发送重置邮件',
    'auth.resetEmailSent': '密码重置邮件已发送至您的电子邮箱。',
    'auth.studentVerificationSuccess': '岭南人邮件验证成功！您现在可以设置密码以完成注册。',
    'auth.backToLogin': '返回登录',
    'auth.backToHome': '返回首页',
    'auth.noAccount': '没有账户？',
    'auth.haveAccount': '已有账户？',
    'auth.contact': '联系',
    'auth.terms': '条款',
    'auth.privacy': '隐私',
    'auth.help': '帮助中心',
    // Auth page titles and descriptions
    'auth.welcomeBack': '欢迎回来',
    'auth.createStudentAccount': '创建您的岭南人账户',
    'auth.fillInfoToCreate': '填写以下信息来创建您的岭南人账户',
    'auth.studentInfoVerification': '岭南人信息验证',
    'auth.passwordSetup': '密码设置',
    'auth.usernameSetup': '用户名设置',
    'auth.username': '用户名',
    'auth.usernamePlaceholder': '请输入您的用户名 (2-10字符)',
    'auth.usernameAvailable': '用户名可用',
    'auth.usernameRules': '用户名规则：',
    'auth.usernameLength': '• 长度：2-10 个字符',
    'auth.usernameSupported': '• 支持：中文、英文、数字、符号、空格',
    'auth.usernameDisplay': '• 用户名将显示在个人资料和评论中',
    'auth.usernameModifiable': '• 可在注册后于设置中修改',
    'auth.usernameSuggestion': '建议用户名：',
    'auth.useSuggestion': '使用',
    'auth.enterAccountInfo': '输入您的账户信息来登录',
    'auth.resetYourPassword': '重置您的密码',
    'auth.signOut': '登出',
    // Toast messages
    'toast.loginSuccess': '登录成功！',
    'toast.welcomeBack': '欢迎回来，{username}！',
    'toast.registerSuccess': '注册成功！',
    'toast.welcomeToApp': '欢迎来到 LingUBible，{username}！',
    'toast.logoutSuccess': '退出成功',
    'toast.goodbye': '再见，{username}！期待您的下次造访。',
    // Search
    'search.placeholder': '搜索课程、讲师...',
    // Buttons
    'button.viewAll': '查看全部',
    'button.review': '评价',
    'button.viewDetails': '查看详情',
    'button.viewProfile': '查看档案',
    // Course/Lecturer Cards
    'card.reviews': '评价',
    'card.students': '学生',
    'card.courses': '课程',
    'card.specialties': '专业领域',
    'card.more': '更多',
    'card.prof': '教授',
    // Difficulty levels
    'difficulty.easy': '简单',
    'difficulty.medium': '中等',
    'difficulty.hard': '困难',
    // Departments
    'department.computerScience': '计算机科学',
    'department.mathematics': '数学',
    'department.english': '英语',
    // Specialties
    'specialty.programming': '程序设计',
    'specialty.dataStructures': '数据结构',
    'specialty.algorithms': '算法',
    'specialty.machineLearning': '机器学习',
    'specialty.calculus': '微积分',
    'specialty.linearAlgebra': '线性代数',
    'specialty.statistics': '统计学',
    'specialty.literature': '文学',
    'specialty.creativeWriting': '创意写作',
    'specialty.poetry': '诗歌',
    'specialty.drama': '戏剧',
    // Sample course titles
    'course.introCS': '计算机科学导论',
    'course.advancedMath': '高等数学',
    'course.englishLit': '英国文学',
    // Sidebar
    'sidebar.myReviews': '我的评价',
    'sidebar.trending': '热门',
    'sidebar.settings': '设置',
    // Password Security
    'password.strength': '密码强度',
    'password.requirements': '密码要求：',
    'password.length': '密码长度为 8-40 个字符',
    'password.uppercase': '包含至少 1 个大写字母',
    'password.lowercase': '包含至少 1 个小写字母',
    'password.special': '包含至少 1 个特殊符号 (!@#$%^&*等)',
    'password.number': '包含至少 1 个数字',
    'password.notCommon': '不是常用密码',
    'password.notLeaked': '不匹配已知泄露密码模式',
    'password.notSimilarToEmail': '不应与学校邮件地址相似',
    'password.lengthSuggestion': '建议使用 12 个字符以上以提高安全性',
    'password.weak': '弱',
    'password.fair': '一般',
    'password.good': '良好',
    'password.strong': '强',
    'password.securityReminder': '安全提醒：',
    'password.schoolEmailWarning': '请不要使用与您的学校邮件账户相同的密码。为了保护您的账户安全，建议为每个服务使用不同的密码。',
    'password.commonPasswordDanger': '危险：',
    'password.commonPasswordMessage': '您使用的是常见密码，这种密码很容易被破解。请选择一个更安全的密码。',
    'password.leakedPasswordRisk': '高风险：',
    'password.leakedPasswordMessage': '此密码匹配已知的泄露密码模式，极易被攻击者猜测。请立即更换为更安全的密码。',
    // Forgot password page
    'auth.emailSent': '邮件已发送',
    'auth.checkYourEmail': '请检查您的邮箱',
    'auth.resetLinkSent': '我们已向',
    'auth.resetLinkSentComplete': '发送了密码重置链接。',
    'auth.checkSpamFolder': '如果您没有收到邮件，请检查垃圾邮件文件夹。',
    'auth.enterSchoolEmail': '输入您的学校邮件地址，我们将发送重置链接给您',
    'auth.schoolEmailPlaceholder': 'student@ln.hk 或 student@ln.edu.hk',
    'auth.useSchoolEmail': '请使用您的学校邮件地址（@ln.hk 或 @ln.edu.hk）',
    'auth.sendResetFailed': '发送重置邮件失败，请稍后再试',
    'auth.sending': '发送中...',
    'auth.securityReminder': '安全提醒',
    'auth.resetLinkExpiry': '重置链接将在 24 小时后过期。如果您没有请求重置密码，请忽略此邮件。',
    'auth.resetLinkWillExpire': '重置链接将在 24 小时后过期',
    'auth.checkEmailInbox': '请检查您的邮箱：',
    'auth.canRetryReset': '您可以重新尝试发送重置邮件',
    'auth.resendReset': '重新发送',
    'auth.sendResetLink': '发送重置链接',
    'auth.studentEmailAddress': '岭南人邮件地址',
    'auth.resetPasswordDescription': '输入您的岭南人邮件地址，我们将发送重置密码的链接给您',
    'auth.emailNotRegistered': '此邮件地址尚未注册。请先注册或检查您的邮件地址。',
    'auth.checkingEmailExists': '检查邮件是否已注册...',
    'auth.emailRegistered': '邮件地址已注册',
    'auth.invalidCredentials': '邮件地址或密码错误，请检查后重试',
    'auth.registrationFailed': '注册失败，请检查资料后重试',
    // Processing
    'auth.processing': '处理中...',
    // Email placeholder
    'auth.emailPlaceholder': 'student@ln.hk 或 student@ln.edu.hk',
    // Email validation
    'auth.invalidStudentEmail': '此邮件地址不是有效的岭南人邮件地址。请使用有效的 @ln.hk 或 @ln.edu.hk 邮件地址。',
    // Email checking status
    'auth.checkingEmail': '检查邮件是否可用...',
    'auth.checkingAccount': '检查账户...',
    'auth.emailAvailable': '邮件地址可用',
    // Student verification
    'verification.title': '岭南人邮件验证',
    'verification.sendCode': '发送验证码',
    'verification.onlyStudentEmails': '只有 @ln.hk 或 @ln.edu.hk 邮件地址的岭南人才能注册',
    'verification.codeExpiry': '验证码有效期为 10 分钟',
    'verification.maxAttempts': '最多可尝试验证 3 次',
    'verification.resendAfter': '后可重新发送',
    'verification.enterCode': '请输入 6 位数验证码',
    'verification.verifying': '验证中...',
    'verification.verify': '验证',
    'verification.resend': '重新',
    'verification.sendingCode': '正在发送验证码...',
    'verification.codeSent': '验证码已发送到您的邮件地址，请检查您的信箱',
    'verification.verifyFailed': '验证失败',
    // Email reminder
    'email.reminder.title': '📧 邮件发送提醒',
    'email.reminder.checkSpam': '如果您没有收到邮件，请检查垃圾邮件文件夹',
    'email.reminder.whitelist': '建议将 noreply@lingubible.com 加入您的邮件白名单',
    'email.reminder.deliveryTime': '邮件发送可能需要 1-2 分钟',
    'email.reminder.contactSupport': '如果 5 分钟后仍未收到邮件，请联系技术支持',
    // Password strength
    'password.strengthLabel': '强度：',
    // Swipe hint
    'swipe.hint': '在屏幕任意位置向右滑动展开菜单',
    'swipe.dismissHint': '滚动页面关闭提示',
    // Cookie consent
    'cookie.title': 'Cookie 使用同意',
    'cookie.description': '本网站使用 Cookie 来确保您获得最佳的浏览体验。',
    'cookie.accept': '我了解',
    'cookie.learnMore': '了解更多',
    'cookie.decline': '拒绝',
    'cookie.close': '关闭',
    // Cookie policy details
    'cookie.policy.title': '我们如何使用 Cookie',
    'cookie.policy.intro': '我们使用 Cookie 来提升您的浏览体验并改善我们的服务。具体如下：',
    'cookie.policy.essential.title': '必要 Cookie',
    'cookie.policy.essential.desc': '这些 Cookie 是网站正常运作所必需的。它们启用基本功能，如页面导航、用户认证和安全性。',
    'cookie.policy.functional.title': '功能性 Cookie',
    'cookie.policy.functional.desc': '这些 Cookie 会记住您的偏好设置（如语言设置、主题和侧边栏状态），以提供个性化体验。',
    'cookie.policy.analytics.title': '分析 Cookie',
    'cookie.policy.analytics.desc': '我们使用这些 Cookie 来了解访客如何与我们网站互动，帮助我们改善性能和用户体验。',
    'cookie.policy.types': '我们使用的 Cookie 类型：',
    'cookie.policy.type1': '• 身份验证 Cookie，保持您的登录状态',
    'cookie.policy.type2': '• 语言偏好 Cookie',
    'cookie.policy.type3': '• 主题和布局偏好 Cookie',
    'cookie.policy.type4': '• 匿名使用分析',
    'cookie.policy.retention': 'Cookie 保存期限',
    'cookie.policy.retention.desc': '大多数 Cookie 会保存最多 1 年，而会话 Cookie 会在您关闭浏览器时删除。',
    'cookie.policy.control': '您的控制权',
    'cookie.policy.control.desc': '您可以通过浏览器设置来控制 Cookie。但是，禁用某些 Cookie 可能会影响网站功能。',
    'cookie.policy.contact': '如果您对我们的 Cookie 政策有疑问，请联系我们。',
    // PWA Install
    'pwa.installAvailable': '应用程序可安装',
    'pwa.installDescription': '安装 LingUBible 获得更好的使用体验',
    'pwa.installBenefits': '更快加载、离线访问和原生应用体验',
    'pwa.install': '安装',
    'pwa.installApp': '安装应用',
    'pwa.howToInstall': '安装方法',
    'pwa.notNow': '稍后再说',
    'pwa.dismiss': '关闭',
    'pwa.gotIt': '我知道了',
    'pwa.installSuccess': '应用安装成功！',
    'pwa.installFailed': '安装失败，请重试。',
    'pwa.alreadyInstalled': '应用已安装',
    'pwa.updateAvailable': '应用更新可用',
    'pwa.updateNow': '立即更新',
    'pwa.updateLater': '稍后更新',
    // User Stats
    'stats.onlineUsers': '在线用户',
    'stats.totalRegistered': '总注册数',
    'stats.todayLogins': '今日登录',
    'stats.thisMonthLogins': '本月登录',
    'stats.usersOnline': '位用户在线',
    'stats.loading': '加载中...',
    // OpenStatus
    'status.operational': 'Operational',
    'status.degraded': 'Degraded',
    'status.down': 'Down',
    'status.checking': 'Checking',
    'status.poweredBy': 'Powered by OpenStatus',
    // Avatar
    'avatar.customize': '自定义头像',
    'avatar.combinations': '种组合',
    'avatar.preview': '预览效果',
    'avatar.randomize': '随机生成',
    'avatar.save': '保存头像',
    'avatar.saving': '保存中...',
    'avatar.resetToDefault': '重置为默认',
    'avatar.animals': '动物',
    'avatar.backgrounds': '背景',
    'avatar.totalStats': '共有 {animals} 种动物 × {backgrounds} 种背景 = {total} 种组合',
    'avatar.saveSuccess': '头像已保存',
    'avatar.saveError': '保存失败，请重试',
    // Background colors
    'background.sunset': '夕阳',
    'background.peach': '蜜桃',
    'background.coral': '珊瑚',
    'background.rose': '玫瑰',
    'background.ocean': '海洋',
    'background.sky': '天空',
    'background.mint': '薄荷',
    'background.forest': '森林',
    'background.lavender': '薰衣草',
    'background.grape': '葡萄',
    'background.plum': '梅子',
    'background.cloud': '云朵',
    'background.stone': '石头',
    'background.warm': '暖阳',
    'background.rainbow': '彩虹',
    'background.aurora': '极光',
    'background.cosmic': '宇宙',
    'background.tropical': '热带',
    'background.fire': '火焰',
    'background.ice': '冰雪',
    // Terms of Service
    'terms.title': '使用条款',
    'terms.lastUpdated': '最后更新：2025年6月5日',
    'terms.welcome': '欢迎使用 LingUBible',
    'terms.acceptance.title': '1. 接受条款',
    'terms.acceptance.content': '使用本网站即表示您同意遵守这些使用条款。如果您不同意这些条款，请不要使用本服务。',
    'terms.conduct.title': '2. 用户行为准则',
    'terms.conduct.content': '为了维护良好的社区环境，用户必须遵守以下行为准则：',
    'terms.conduct.noSwearing': '• 禁止使用粗言秽语或不当言论',
    'terms.conduct.noPersonalAttacks': '• 禁止人身攻击或针对个人的恶意言论',
    'terms.conduct.noSpam': '• 禁止发送垃圾信息或重复无意义的内容',
    'terms.conduct.respectful': '• 保持尊重和建设性的讨论态度',
    'terms.conduct.violation': '违反上述准则可能导致账户被暂停或永久封禁',
    'terms.moderation.title': '3. 内容管理',
    'terms.moderation.content': '我们保留审核和管理平台内容的权利：',
    'terms.moderation.removal': '• 不当评论将被删除，且不会事先通知',
    'terms.moderation.standards': '• 我们致力于维护高质量的讨论环境',
    'terms.moderation.discretion': '• 管理决定将基于社区准则和管理团队的判断',
    'terms.privacy.title': '4. 隐私保护',
    'terms.privacy.content': '我们承诺保护您的隐私：',
    'terms.privacy.anonymity': '• 评论者的身份将被严格保密',
    'terms.privacy.noDisclosure': '• 我们不会向任何第三方披露用户身份信息',
    'terms.privacy.dataCollection': '• 详细的数据收集政策请参阅隐私政策',
    'terms.changes.title': '5. 条款变更',
    'terms.changes.content': '我们可能会不时更新这些条款。重大变更将通过网站公告通知用户。',
    'terms.contact.title': '8. 联系我们',
    'terms.contact.content': '如果您对这些条款有任何疑问，请通过网站联系功能与我们联系。',
    'terms.username.title': '6. 用户名政策',
    'terms.username.content': '用户需对其选择的用户名负责：',
    'terms.username.offensive': '• 冒犯性、不当或误导性的用户名可能会在不通知的情况下被更改',
    'terms.username.discretion': '• 用户名更改由管理团队自行决定',
    'terms.username.responsibility': '• 用户有责任确保其用户名符合社区标准',
    'terms.content.title': '7. 内容政策',
    'terms.content.content': '为了维护专注且相关的讨论环境：',
    'terms.content.noPolitics': '• 不允许政治讨论',
    'terms.content.noReligion': '• 不允许宗教讨论',
    'terms.content.noUnrelated': '• 不允许与网站目的无关的内容',
    'terms.content.removal': '无关或不当内容将在不通知的情况下被删除',
    'terms.content.focus': '• 请将讨论重点放在课程和讲师评价上',
    // Privacy Policy
    'privacy.title': '隐私政策',
    'privacy.lastUpdated': '最后更新：2025年6月5日',
    'privacy.intro': '本隐私政策说明我们如何收集、使用和保护您的个人信息。',
    'privacy.dataCollection.title': '1. 数据收集',
    'privacy.dataCollection.content': '为了提供更好的服务和维护平台安全，我们会收集以下信息：',
    'privacy.dataCollection.sessionTime': '会话时间：用于分析用户活跃度和改善服务质量',
    'privacy.dataCollection.ipAddress': 'IP 地址：用于安全监控和防止滥用行为',
    'privacy.dataCollection.userAgent': '浏览器信息：用于优化网站兼容性和用户体验',
    'privacy.dataCollection.purpose': '收集这些信息的目的是为了：',
    'privacy.dataCollection.security': '• 维护平台安全，防止恶意攻击和滥用',
    'privacy.dataCollection.analytics': '• 分析用户行为，改善服务质量',
    'privacy.dataCollection.technical': '• 提供技术支持和故障排除',
    'privacy.dataCollection.compliance': '• 遵守法律法规要求',
    'privacy.anonymity.title': '2. 匿名性保护',
    'privacy.anonymity.content': '我们高度重视用户的匿名性：',
    'privacy.anonymity.strictConfidentiality': '评论者的身份信息将被严格保密',
    'privacy.anonymity.noDisclosure': '我们承诺不会向任何个人、组织或第三方披露用户的真实身份',
    'privacy.anonymity.internalAccess': '只有授权的技术人员在必要时才能访问用户数据，且仅用于技术维护',
    'privacy.anonymity.legalProtection': '除非法律明确要求，否则我们不会主动披露用户信息',
    'privacy.dataRetention.title': '3. 数据保留',
    'privacy.dataRetention.content': '我们的数据保留政策如下：',
    'privacy.dataRetention.sessionData': '• 会话数据：保留 30 天后自动删除',
    'privacy.dataRetention.logData': '• 日志数据：保留 90 天用于安全分析',
    'privacy.dataRetention.userContent': '• 用户内容：根据用户要求可随时删除',
    'privacy.dataSecurity.title': '4. 数据安全',
    'privacy.dataSecurity.content': '我们采用多重安全措施保护您的数据：',
    'privacy.dataSecurity.encryption': '• 使用 HTTPS 加密传输所有数据',
    'privacy.dataSecurity.accessControl': '• 实施严格的访问控制和权限管理',
    'privacy.dataSecurity.monitoring': '• 24/7 安全监控和异常检测',
    'privacy.dataSecurity.updates': '• 定期更新安全措施和系统补丁',
    'privacy.userRights.title': '5. 用户权利',
    'privacy.userRights.content': '您拥有以下权利：',
    'privacy.userRights.access': '• 查询我们收集的关于您的信息',
    'privacy.userRights.correction': '• 要求更正不准确的个人信息',
    'privacy.userRights.deletion': '• 要求删除您的个人数据',
    'privacy.userRights.portability': '• 要求导出您的数据',
    'privacy.cookies.title': '6. Cookie 使用',
    'privacy.cookies.content': '我们使用 Cookie 来改善您的浏览体验。详细信息请参阅我们的 Cookie 政策。',
    'privacy.changes.title': '7. 政策变更',
    'privacy.changes.content': '我们可能会不时更新此隐私政策。重大变更将通过网站公告通知用户。',
    'privacy.contact.title': '8. 联系我们',
    'privacy.contact.content': '如果您对此隐私政策有任何疑问或需要行使您的权利，请通过网站联系功能与我们联系。',
    // Privacy badges and labels
    'privacy.important': '重要',
    'privacy.days30': '30 天',
    'privacy.days90': '90 天',
    'privacy.anytime': '随时',
    // Common
    'common.backToHome': '返回首页',
    'common.lastUpdated': '最后更新',
    // Terms agreement
    'auth.termsAgreement': '注册即表示您同意我们的使用条款和隐私政策',
    'auth.termsAgreementShort': '注册即表示您同意我们的',
    'auth.and': '和',
    'auth.termsCheckbox': '我已阅读并同意',
    'auth.termsOfService': '使用条款',
    'auth.privacyPolicy': '隐私政策',
    'auth.mustAgreeTerms': '您必须同意使用条款和隐私政策才能继续',
    // Contact Page
    'contact.title': '联系我们',
    'contact.subtitle': '有任何问题或建议？我们很乐意听取您的意见',
    'contact.methods': '联系方式',
    'contact.email': '电子邮箱',
    'contact.github': 'GitHub',
    'contact.developer': '开发者',
    'contact.privacy': '隐私保护',
    'contact.privacyMessage': '我们承诺保护您的隐私。您的联系信息仅用于回复您的查询，不会与第三方分享。',
    'contact.faq': '常见问题',
    'contact.faqReport': '如何报告不当内容？',
    'contact.faqReportAnswer': '请发送电子邮件至 <a href="mailto:support@lingubible.com" class="underline hover:no-underline">support@lingubible.com</a> 向我们报告任何违反社区准则的内容。',
    'contact.faqDelete': '如何删除我的评论？',
    'contact.faqDeleteAnswer': '请联系我们并提供相关信息，我们会协助您处理。',
    'contact.faqTechnical': '技术问题回报',
    'contact.faqTechnicalAnswer': '遇到网站技术问题？请详细描述问题并发送给我们。',
    'contact.sendMessage': '发送消息',
    'contact.name': '姓名',
    'contact.namePlaceholder': '请输入您的姓名',
    'contact.emailPlaceholder': '请输入您的电子邮箱',
    'contact.subject': '主题',
    'contact.subjectPlaceholder': '请输入消息主题',
    'contact.message': '消息内容',
    'contact.messagePlaceholder': '请详细描述您的问题或建议...',
    'contact.sending': '发送中...',
    'contact.send': '发送消息',
    'contact.successMessage': '消息发送成功！我们会尽快回复您。',
    'contact.errorMessage': '发送失败，请稍后再试或直接发送邮件至 support@lingubible.com',
    // User Settings Page
    'settings.title': '用户设置',
    'settings.subtitle': '管理您的个人资料和偏好设置',
    'settings.backToHome': '返回首页',
    'settings.profile': '个人资料',
    'settings.profileDescription': '更新您的个人资料信息',
    'settings.email': '电子邮箱',
    'settings.emailReadOnly': '电子邮箱地址无法修改',
    'settings.username': '用户名',
    'settings.usernamePlaceholder': '输入您的用户名 (2-10字符，可留空)',
    'settings.usernameAvailable': '用户名可用',
    'settings.usernameRules': '用户名规则：',
    'settings.usernameLength': '• 长度：2-10 个字符（可留空）',
    'settings.usernameSupported': '• 支持：中文、英文、数字、符号、空格',
    'settings.usernameEmpty': '• 留空时将显示邮箱前缀作为用户名',
    'settings.usernameDisplay': '• 用户名将显示在个人资料和评论中',
    'settings.saving': '保存中...',
    'settings.saveChanges': '保存更改',
    'settings.reset': '重置',
    'settings.saveSuccess': '✅ 保存成功',
    'settings.saveFailed': '保存失败',
    'settings.usernameUpdated': '用户名已更新为：{username}',
    'settings.usernameCleared': '用户名已清空，将显示邮箱前缀',
    'settings.updateError': '更新用户名时发生错误，请稍后再试',
    'settings.loginRequired': '请先登录以访问用户设置',
    'settings.login': '登录',
    // Danger Zone
    'settings.dangerZone.title': '危险区',
    'settings.dangerZone.description': '账户管理操作',
    'settings.dangerZone.warning': '此操作将暂时禁用您的账户。请谨慎进行。',
    'settings.dangerZone.deleteAccount': '禁用账户',
    'settings.dangerZone.confirmDelete': '确认账户禁用',
    'settings.dangerZone.confirmDeleteDesc': '此操作将暂时禁用您的账户。您将无法登录，直到重新启用为止。',
    'settings.dangerZone.irreversibleWarning': '您的账户将被暂时禁用。您可以通过重新登录来重新启用。',
    'settings.dangerZone.confirmEmailLabel': '输入您的电子邮件地址以确认',
    'settings.dangerZone.confirmEmailDesc': '请输入您的电子邮件地址完全相同以确认禁用。',
    'settings.dangerZone.cancel': '取消',
    'settings.dangerZone.confirmDeleteButton': '禁用我的账户',
    'settings.dangerZone.deleting': '禁用中...',
    'settings.dangerZone.completeDeleteInfo': '如需完全删除账户，请发送邮件至 contact@lingubible.com',
    'settings.dangerZone.reEnableInfo': '如需重新启用被禁用的账户，只需使用您的凭证重新登录即可。',
    'settings.deleteAccount.emailMismatch': '电子邮件不匹配',
    'settings.deleteAccount.emailMismatchDesc': '您输入的电子邮件地址与您的账户电子邮件地址不匹配。',
    'settings.deleteAccount.success': '账户已禁用',
    'settings.deleteAccount.successDesc': '您的账户已暂时禁用。您可以通过重新登录来重新启用。',
    'settings.deleteAccount.failed': '禁用失败',
    'settings.deleteAccount.failedDesc': '禁用账户失败，请稍后再试。',
    'auth.showPassword': '显示密码',
    'auth.hidePassword': '隐藏密码',
  },
};

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguageState] = useState<Language>(getInitialLanguage);

  // Update language and save to cookie
  const setLanguage = (newLanguage: Language) => {
    console.log('切換語言到:', newLanguage);
    setLanguageState(newLanguage);
    setCookie('language', newLanguage);
    
    // 觸發 PWA manifest 更新
    if (typeof window !== 'undefined' && window.updatePWAManifest) {
      setTimeout(() => {
        window.updatePWAManifest();
      }, 100); // 稍微延遲確保 cookie 已設置
    }
  };

  // 監聽系統語言變化（可選功能）
  useEffect(() => {
    const handleLanguageChange = () => {
      // 只有在沒有手動設置語言時才響應系統語言變化
      const savedLanguage = getCookie('language');
      if (!savedLanguage) {
        const newLanguage = getInitialLanguage();
        setLanguageState(newLanguage);
      }
    };

    // 監聽語言變化事件（某些瀏覽器支持）
    window.addEventListener('languagechange', handleLanguageChange);
    
    return () => {
      window.removeEventListener('languagechange', handleLanguageChange);
    };
  }, []);

  const t = (key: string, params?: Record<string, any>): any => {
    let translation = translations[language][key] || key;
    
    // 如果有參數，進行字符串替換
    if (params && typeof translation === 'string') {
      Object.keys(params).forEach(paramKey => {
        const placeholder = `{${paramKey}}`;
        translation = translation.replace(new RegExp(placeholder, 'g'), params[paramKey]);
      });
    }
    
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
